objects=\
get_reduced_radius.o\
getReducedRadius.o\
hermite_curve_recovering.o\
mapping_func.o\
mapping_func_kernel.o\
point_add.o\
point_container_free.o\
point_container_new.o\
point_get.o\
point_set.o\
scribble_b.o\
scribble.o\
seq_hermite_write_to_image.o\
tracing_path_adjust.o\
tracing_path_load.o\
tracing_path_write_to_image.o
